server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;
  location /api/inventory/ { proxy_pass http://inventory-api:8000/api/inventory/; }
  location /api/distribution/ { proxy_pass http://logistics-api:8000/api/distribution/; }
  location /api/operations/ { proxy_pass http://operations-api:8000/api/operations/; }
  location /api/fulfillment/ { proxy_pass http://fulfillment-api:8000/api/fulfillment/; }
  location /health/inventory { proxy_pass http://inventory-api:8000/health; }
  location /health/logistics { proxy_pass http://logistics-api:8000/health; }
  location /health/operations { proxy_pass http://operations-api:8000/health; }
  location /health/fulfillment { proxy_pass http://fulfillment-api:8000/health; }
}
